ARG DOCKER_REGISTRY
ARG POSTGRES_BASE_IMAGE
ARG POSTGRES_USER
ARG POSTGRES_PASSWORD
ARG POSTGRES_DB

FROM $DOCKER_REGISTRY/$POSTGRES_BASE_IMAGE AS final
ENV POSTGRES_USER=$POSTGRES_USER
ENV POSTGRES_PASSWORD=$POSTGRES_PASSWORD
ENV POSTGRES_DB=$POSTGRES_DB

EXPOSE 5432

USER postgres