services:
  fit-child-postgres:
    container_name: fit-child-postgres
    image: fit-child/postgres:$APP_VERSION
    build:
      context: ../
      dockerfile: ./docker/Postgres.dockerfile
      args:
        DOCKER_REGISTRY: $DOCKER_REGISTRY
        POSTGRES_BASE_IMAGE: $POSTGRES_BASE_IMAGE
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/pgsql/data

volumes:
  pg_data:
